### ISSUE TITLE
Unable to install pyrocksdb against rocksdb 3.3

### ISSUE THREAD

**Issue by dmsimard** [stephan-hof/pyrocksdb#13]
Hi,

I was able to successfully build pyrocksdb against rocksdb up until 3.2.
Installation does not work in my experience with the newly released 3.3.

Here is how I reproduced (Ubuntu 14.04 LTS):

```
apt-get install build-essential libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev python-pip python-dev git
cd /usr/local/src
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
git checkout 3.3.fb
make librocksdb.so
cp librocksdb.so /usr/local/lib
mkdir -p /usr/local/include/rocksdb/
cp -r ./include/* /usr/local/include/
pip install "Cython>=0.20"
pip install git+git://github.com/stephan-hof/pyrocksdb.git

# pip install git+git://github.com/stephan-hof/pyrocksdb.git
Downloading/unpacking git+git://github.com/stephan-hof/pyrocksdb.git
  Cloning git://github.com/stephan-hof/pyrocksdb.git to /tmp/pip-zRO8z4-build
  Running setup.py (path:/tmp/pip-zRO8z4-build/setup.py) egg_info for package from git+git://github.com/stephan-hof/pyrocksdb.git
    missing cimport in module 'pair': /usr/local/lib/python2.7/dist-packages/Cython/Includes/libcpp/deque.pxd
    Compiling rocksdb/_rocksdb.pyx because it changed.
    Cythonizing rocksdb/_rocksdb.pyx

Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from pyrocksdb==0.3)
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.20 in /usr/local/lib/python2.7/dist-packages (from pyrocksdb==0.3)
Installing collected packages: pyrocksdb
  Running setup.py install for pyrocksdb
    missing cimport in module 'pair': /usr/local/lib/python2.7/dist-packages/Cython/Includes/libcpp/deque.pxd

    building 'rocksdb._rocksdb' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c rocksdb/_rocksdb.cpp -o build/temp.linux-x86_64-2.7/rocksdb/_rocksdb.o -std=gnu++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    rocksdb/_rocksdb.cpp: In function ‘PyObject* __pyx_pf_7rocksdb_8_rocksdb_19PyBloomFilterPolicy_6create_filter(__pyx_obj_7rocksdb_8_rocksdb_PyBloomFilterPolicy*, PyObject*)’:
    rocksdb/_rocksdb.cpp:5584:99: warning: conversion to ‘int’ from ‘std::vector<rocksdb::Slice>::size_type {aka long unsigned int}’ may alter its value [-Wconversion]
         __pyx_v_self->policy->CreateFilter(py_rocks::vector_data(__pyx_v_c_keys), __pyx_v_c_keys.size(), (&__pyx_v_dst));
                                                                                                       ^
    rocksdb/_rocksdb.cpp: In function ‘int __pyx_pf_7rocksdb_8_rocksdb_27TotalOrderPlainTableFactory___init__(__pyx_obj_7rocksdb_8_rocksdb_TotalOrderPlainTableFactory*, PyObject*, PyObject*, PyObject*)’:
    rocksdb/_rocksdb.cpp:8988:44: error: ‘NewTotalOrderPlainTableFactory’ is not a member of ‘rocksdb’
         __pyx_v_self->__pyx_base.factory.reset(rocksdb::NewTotalOrderPlainTableFactory(__pyx_t_1, __pyx_t_2, __pyx_t_3));
                                                ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-zRO8z4-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vwXPvW-record/install-record.txt --single-version-externally-managed --compile:
    missing cimport in module 'pair': /usr/local/lib/python2.7/dist-packages/Cython/Includes/libcpp/deque.pxd

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/rocksdb

copying rocksdb/interfaces.py -> build/lib.linux-x86_64-2.7/rocksdb

copying rocksdb/errors.py -> build/lib.linux-x86_64-2.7/rocksdb

copying rocksdb/__init__.py -> build/lib.linux-x86_64-2.7/rocksdb

creating build/lib.linux-x86_64-2.7/rocksdb/tests

copying rocksdb/tests/test_options.py -> build/lib.linux-x86_64-2.7/rocksdb/tests

copying rocksdb/tests/test_db.py -> build/lib.linux-x86_64-2.7/rocksdb/tests

copying rocksdb/tests/__init__.py -> build/lib.linux-x86_64-2.7/rocksdb/tests

running egg_info

creating pyrocksdb.egg-info

writing requirements to pyrocksdb.egg-info/requires.txt

writing pyrocksdb.egg-info/PKG-INFO

writing top-level names to pyrocksdb.egg-info/top_level.txt

writing dependency_links to pyrocksdb.egg-info/dependency_links.txt

writing manifest file 'pyrocksdb.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



reading manifest file 'pyrocksdb.egg-info/SOURCES.txt'

writing manifest file 'pyrocksdb.egg-info/SOURCES.txt'

copying rocksdb/_rocksdb.cpp -> build/lib.linux-x86_64-2.7/rocksdb

running build_ext

building 'rocksdb._rocksdb' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/rocksdb

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c rocksdb/_rocksdb.cpp -o build/temp.linux-x86_64-2.7/rocksdb/_rocksdb.o -std=gnu++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

rocksdb/_rocksdb.cpp: In function ‘PyObject* __pyx_pf_7rocksdb_8_rocksdb_19PyBloomFilterPolicy_6create_filter(__pyx_obj_7rocksdb_8_rocksdb_PyBloomFilterPolicy*, PyObject*)’:

rocksdb/_rocksdb.cpp:5584:99: warning: conversion to ‘int’ from ‘std::vector<rocksdb::Slice>::size_type {aka long unsigned int}’ may alter its value [-Wconversion]

     __pyx_v_self->policy->CreateFilter(py_rocks::vector_data(__pyx_v_c_keys), __pyx_v_c_keys.size(), (&__pyx_v_dst));

                                                                                                   ^

rocksdb/_rocksdb.cpp: In function ‘int __pyx_pf_7rocksdb_8_rocksdb_27TotalOrderPlainTableFactory___init__(__pyx_obj_7rocksdb_8_rocksdb_TotalOrderPlainTableFactory*, PyObject*, PyObject*, PyObject*)’:

rocksdb/_rocksdb.cpp:8988:44: error: ‘NewTotalOrderPlainTableFactory’ is not a member of ‘rocksdb’

     __pyx_v_self->__pyx_base.factory.reset(rocksdb::NewTotalOrderPlainTableFactory(__pyx_t_1, __pyx_t_2, __pyx_t_3));

                                            ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-zRO8z4-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vwXPvW-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-zRO8z4-build
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

**Comment by elad** [comment]
I'm getting the same error as @zongshoujin. Is this project still under active development...?

EDIT: Solved. Python 2.6 requires Pyrex installed.
