### ISSUE TITLE
undefined symbol: _ZTIN7rocksdb10ComparatorE

### ISSUE THREAD

**Issue by azhuoinfogs** [stephan-hof/pyrocksdb#57]
python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rocksdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python2.7/dist-packages/rocksdb/_rocksdb.so: undefined symbol: _ZTIN7rocksdb10ComparatorE

**Comment by baraiyaraj** [comment]
Having same issue. Please provide some solution.

**Comment by baraiyaraj** [comment]
I was able to solve the above problem. Please delete the copy of your python rocks-db and try the steps below:
https://github.com/rajbaraiyaa/python-rocksdb-/blob/master/install_steps

I was successfully able to install it with the steps mentioned in the link.

**Comment by richael02** [comment]
@azhuoinfogs  I met this problem too. Have you figured out the solution ?
@rajbaraiyaa  I install  pyrocksdb by the same steps as you, but there still exists the ImportError.

**Comment by ali8zake** [comment]
hello
a)
i use the install_step, faild by clock_time not fund ,but i export LD_PRELOAD, aslo LDFLAGS = -lr ,aslo failed
b) git clone master ,make share_lib,can make ok
then pip install 
import failed 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/rocksdb/__init__.py", line 1, in <module>
    from ._rocksdb import *
ImportError: /usr/local/lib/python2.7/site-packages/rocksdb/_rocksdb.so: undefined symbol: _ZTIN7rocksdb24AssociativeMergeOperatorE

thanks
